#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sof-bin
Version  : 6c721969e200706db06ab468c5207384ab339739
Release  : 4
URL      : https://github.com/thesofproject/sof-bin/archive/6c721969e200706db06ab468c5207384ab339739.tar.gz
Source0  : https://github.com/thesofproject/sof-bin/archive/6c721969e200706db06ab468c5207384ab339739.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: sof-bin-license = %{version}-%{release}
Patch1: 0001-Convert-go.sh-script-into-a-classic-Makefile-with-DE.patch

%description
# SOF Firmware and Topology Binaries
This is the living area and distribution channel for SOF firmware and topology
binaries. It's still very much WiP and may churn a little until things
settle down.

%package license
Summary: license components for the sof-bin package.
Group: Default

%description license
license components for the sof-bin package.


%prep
%setup -q -n sof-bin-6c721969e200706db06ab468c5207384ab339739
cd %{_builddir}/sof-bin-6c721969e200706db06ab468c5207384ab339739
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586372228
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1586372228
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sof-bin
cp %{_builddir}/sof-bin-6c721969e200706db06ab468c5207384ab339739/LICENCE.Intel %{buildroot}/usr/share/package-licenses/sof-bin/b052da06a67e96a1d3ca22f4630bf7956ea88d5a
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/firmware/intel/sof-tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-da7219.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-demux-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-dmic-2ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-dmic-4ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-dmic-a2ch-b2ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-dmic-a2ch-b4ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-dmic-a2ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-dmic-a4ch-b2ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-dmic-b2ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-eq-dmic.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-eq-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-keyword-detect.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-pcm512x-nohdmi.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-rt298.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-src-50khz-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-src-dmic.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-src-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-tdf8532.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-apl-wm8804.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-bdw-rt286.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-bdw-rt5640.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-byt-da7213.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-byt-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-byt-rt5640.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-byt-rt5645.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-byt-rt5651.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-byt-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cht-max98090.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cht-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cht-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cht-src-50khz-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-demux-rt5682-max98357a.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-demux-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-rt1011-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-rt5682-kwd.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-rt5682-max98357a.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-rt700.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-rt711-rt1308-mono-rt715.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-rt711-rt1308-rt715.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cml-src-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cnl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-cnl-rt274.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-glk-da7219-kwd.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-glk-da7219.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-glk-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-hda-generic-2ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-hda-generic-4ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-hda-generic-idisp-2ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-hda-generic-idisp-4ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-hda-generic-idisp.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-hda-generic.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-hsw-rt5640.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-icl-dmic-4ch.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-icl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-icl-rt5682-kwd.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-icl-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-icl-rt700.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-icl-rt711-rt1308-rt715-hdmi.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-icl-rt711-rt1308-rt715.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-tgl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-tgl-rt711-rt1308-nohdmi.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-tgl-rt711-rt1308.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-whl-demux-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-whl-rt5682-kwd.tplg
/usr/lib/firmware/intel/sof-tplg-v1.4.2/sof-whl-rt5682.tplg
/usr/lib/firmware/intel/sof/sof-apl.ri
/usr/lib/firmware/intel/sof/sof-bdw.ri
/usr/lib/firmware/intel/sof/sof-byt.ri
/usr/lib/firmware/intel/sof/sof-cfl.ri
/usr/lib/firmware/intel/sof/sof-cht.ri
/usr/lib/firmware/intel/sof/sof-cml.ri
/usr/lib/firmware/intel/sof/sof-cnl.ri
/usr/lib/firmware/intel/sof/sof-glk.ri
/usr/lib/firmware/intel/sof/sof-icl.ri
/usr/lib/firmware/intel/sof/v1.4.2/intel-signed/sof-apl-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/intel-signed/sof-cnl-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/intel-signed/sof-icl-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/public-signed/sof-apl-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/public-signed/sof-cnl-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/public-signed/sof-icl-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/sof-apl-v1.4.2.ldc
/usr/lib/firmware/intel/sof/v1.4.2/sof-bdw-v1.4.2.ldc
/usr/lib/firmware/intel/sof/v1.4.2/sof-bdw-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/sof-byt-v1.4.2.ldc
/usr/lib/firmware/intel/sof/v1.4.2/sof-byt-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/sof-cht-v1.4.2.ldc
/usr/lib/firmware/intel/sof/v1.4.2/sof-cht-v1.4.2.ri
/usr/lib/firmware/intel/sof/v1.4.2/sof-cnl-v1.4.2.ldc
/usr/lib/firmware/intel/sof/v1.4.2/sof-icl-v1.4.2.ldc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sof-bin/b052da06a67e96a1d3ca22f4630bf7956ea88d5a
